// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-bNska-ifXL0Rvcyji7u80K0x4zgNx0A',
    appId: '1:637618160288:web:93690413e70bc523f4ffc5',
    messagingSenderId: '637618160288',
    projectId: 'agble-36436',
    authDomain: 'agble-36436.firebaseapp.com',
    storageBucket: 'agble-36436.appspot.com',
    measurementId: 'G-BV05K629P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQanDwFL4t_w2u2KS1oSklDTueV2M9_8',
    appId: '1:637618160288:android:ecb68f7ac6d51934f4ffc5',
    messagingSenderId: '637618160288',
    projectId: 'agble-36436',
    storageBucket: 'agble-36436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYaEpMdd7xy37dKTxbL47Cg8_edfa-n7A',
    appId: '1:637618160288:ios:2365155120b8b568f4ffc5',
    messagingSenderId: '637618160288',
    projectId: 'agble-36436',
    storageBucket: 'agble-36436.appspot.com',
    iosClientId: '637618160288-d3qe5jo7n5ki8r2t6hqvnmndvegk7819.apps.googleusercontent.com',
    iosBundleId: 'com.example.agble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYaEpMdd7xy37dKTxbL47Cg8_edfa-n7A',
    appId: '1:637618160288:ios:4952092a403280c1f4ffc5',
    messagingSenderId: '637618160288',
    projectId: 'agble-36436',
    storageBucket: 'agble-36436.appspot.com',
    iosClientId: '637618160288-hsv16frf32ghjcfeda190gajer72tbgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.agble.RunnerTests',
  );
}
